import pytest
from models import (
    Aplicaciones,
    Composiciones_Principales,
    Unidades_Medidas,
    Medidas,
    Requerimientos_Agua,
    Colores,
    Entornos_Ideales,
    Tipos_Suelos,
    Temporadas_Plantacion,
    Plantas,
    Insumos,
    Insumos_Unidades,
    Aplicaciones_Insumos,
    Categorias,
    Subcategorias,
    Plantas_Subcategoria,
    Insumos_Subcategoria,
    Tipo_Movimientos,
    Stock,
    Roles,
    Rutas,
    Rutas_roles,
    Usuarios,
    Cliente_Categoria,
    tipos_pagos,
    Ventas,
    Movimientos_kardex,
    Detalle_ventas,
    Devoluciones,
    Detalle_devoluciones,
    Proveedores,
    Compras,
    Detalles_Compra,
    Listas_deseo,
    configuracion_sistema,
)

@pytest.mark.parametrize("model,kwargs", [
    (Aplicaciones, {"id": 1, "aplicacion": "Fertilizante", "descripcion": "Aumenta el rendimiento"}),
    (Composiciones_Principales, {"id": 1, "composicion": "Nitrógeno", "descripcion": "Elemento esencial"}),
    (Unidades_Medidas, {"id": 1, "unidad_medida": "Litros", "abreviatura": "L"}),
    (Medidas, {"id": 1, "medida": "50 ml"}),
    (Requerimientos_Agua, {"id": 1, "requerimiento_agua": "Moderado", "descripcion": "Riego semanal"}),
    (Colores, {"id": 1, "color": "Verde"}),
    (Entornos_Ideales, {"id": 1, "entorno": "Exterior", "descripcion": "Ambientes soleados"}),
    (Tipos_Suelos, {"id": 1, "tipo_suelo": "Arenoso", "descripcion": "Buen drenaje"}),
    (Temporadas_Plantacion, {"id": 1, "temporada": "Primavera", "descripcion": "Clima cálido"}),
    (Plantas, {"id": 1, "nombre": "Rosa", "descripcion": "Flor roja", "entorno_ideal_id": 1,
               "requerimiento_agua_id": 1, "tipo_suelo_id": 1, "temporada_plantacion_id": 1,
               "precio_venta": 5.0}),
    (Insumos, {"id": 1, "nombre": "Fertilizante Compuesto", "tipo_insumo": "Químico",
               "composicion_principal_id": 1, "precio_venta": 20.0}),
    (Insumos_Unidades, {"id": 1, "unidad_medida_id": 1, "insumo_id": 1}),
    (Aplicaciones_Insumos, {"id": 1, "aplicacion_id": 1, "insumo_id": 1}),
    (Categorias, {"id": 1, "categoria": "Decorativas", "descripcion": "Plantas para decoración", "estado": True}),
    (Subcategorias, {"id": 1, "categoria_id": 1, "subcategoria": "Interior", "descripcion": "Para interiores", "estado": True}),
    (Plantas_Subcategoria, {"id": 1, "subcategoria_id": 1, "planta_id": 1}),
    (Insumos_Subcategoria, {"id": 1, "subcategoria_id": 1, "insumo_id": 1}),
    (Tipo_Movimientos, {"id": 1, "tipo_movimiento": "Entrada", "descripcion": "Compra de insumos"}),
    (Stock, {"id": 1, "planta_id": 1, "insumo_id": None, "cantidad": 100.0, "kardex_id": 1, "estado": "Activo"}),
    (Roles, {"id": 1, "rol": "Administrador"}),
    (Rutas, {"id": 1, "ruta": "/admin"}),
    (Rutas_roles, {"id": 1, "rol_id": 1, "ruta_id": 1}),
    (Usuarios, {"id": 1, "nombre_completo": "Juan Pérez", "correo": "juan@correo.com", "clave": "1234", "rol_id": 1, "estado": True}),
    (Cliente_Categoria, {"id": 1, "categoria": "Mayorista"}),
    (tipos_pagos, {"id": 1, "tipo_pago": "Efectivo"}),
    (Ventas, {"id": 1, "nombre_cliente": "Cliente 1", "usuario_id": 1, "id_cliente_categoria": 1, "id_tipo_pago": 1, "fecha_venta": "2024-01-01", "total": 100.0, "estado": True}),
    (Movimientos_kardex, {"id": 1, "planta_id": 1, "insumo_id": None, "cantidad": 10.0, "tipo_movimiento_id": 1, "precio_unitario": 5.0, "fecha_movimiento": "2024-01-01"}),
    (Detalle_ventas, {"id": 1, "venta_id": 1, "kardex_id": 1, "cantidad": 2.0, "precio_unitario": 5.0, "subtotal": 10.0}),
    (Devoluciones, {"id": 1, "venta_id": 1, "fecha_devolucion": "2024-01-01", "total": 5.0}),
    (Detalle_devoluciones, {"id": 1, "devolucion_id": 1, "kardex_id": 1, "cantidad": 1.0, "precio_unitario": 5.0, "subtotal": 5.0}),
    (Proveedores, {"id": 1, "nombre_proveedor": "Proveedor SA", "correo_electronico": "contacto@proveedor.com", "telefono": 12345678, "direccion": "Calle Principal", "estado": True}),
    (Compras, {"id": 1, "proveedor_id": 1, "usuario_id": 1, "fecha_compra": "2024-01-01", "total": 50.0}),
    (Detalles_Compra, {"id": 1, "compra_id": 1, "kardex_id": 1, "cantidad": 10.0, "precio_unitario": 5.0, "subtotal": 50.0}),
    (Listas_deseo, {"lista_deseo_id": 1, "usuario_id": 1, "planta_id": 1, "fecha": "2024-01-01"}),
    (configuracion_sistema, {"id": 1, "nombre_empresa": "Mi Empresa", "direccion": "Dirección Central", "telefono": "12345678", "email": "info@empresa.com", "numero_ruc": "1234567890", "logo_empresa_url": "https://logo.com/logo.png", "link_facebook": "https://facebook.com/empresa", "link_instagram": "https://instagram.com/empresa", "link_tiktok": "https://tiktok.com/empresa", "link_whatsapp": "https://wa.me/12345678"}),
])
def test_model_creation(model, kwargs):
    instance = model(**kwargs)
    for key, value in kwargs.items():
        assert getattr(instance, key) == value
    print(f"{model.__name__} creado exitosamente: {kwargs}")
